# Generated by Django 6.0 on 2025-12-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Метаданные (кнопки, ссылки)'),
        ),
    ]
