# Generated by Django 6.0 on 2026-01-18 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.AlterField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=False, verbose_name='Email уведомления')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='Push уведомления (Мобильные)')),
                ('browser_enabled', models.BooleanField(default=True, verbose_name='В браузере (Колокольчик)')),
                ('sound_enabled', models.BooleanField(default=True, verbose_name='Звук уведомлений')),
                ('notify_medical', models.BooleanField(default=True, verbose_name='Медицинские события')),
                ('notify_care', models.BooleanField(default=True, verbose_name='Уход и Груминг')),
                ('notify_reproduction', models.BooleanField(default=True, verbose_name='Репродукция')),
                ('notify_system', models.BooleanField(default=True, verbose_name='Системные новости')),
                ('reminder_time_minutes', models.IntegerField(choices=[(15, 'За 15 минут'), (30, 'За 30 минут'), (60, 'За 1 час'), (120, 'За 2 часа'), (1440, 'За 24 часа (1 день)')], default=1440, verbose_name='За сколько напоминать')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
