"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG') == 'True'

ALLOWED_HOSTS = [
    "localhost", 
    "127.0.0.1", 
    "careyour.pet", 
    "www.careyour.pet", 
    "193.180.213.143"
]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'modeltranslation',
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    'django.contrib.postgres',
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    'users',
    'pets',
    'simple_history',
    'notifications',
    'channels',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

# Указываем Django использовать нашу модель пользователя
AUTH_USER_MODEL = 'users.User'

# CORS (Для разработки разрешаем всё, для продакшена ограничим)
CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOWED_ORIGINS = [
    "https://careyour.pet",
    "https://www.careyour.pet",
    "http://localhost:3000",
    "http://127.0.0.1:8000",
]

CSRF_TRUSTED_ORIGINS = [
    "https://careyour.pet",
    "https://www.careyour.pet",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8000",
]

CORS_ALLOW_CREDENTIALS = True
# DRF Config
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# URL, по которому файлы будут доступны в браузере
MEDIA_URL = '/media/'

# Физическая папка на компьютере, куда будут падать файлы
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

SIMPLE_JWT = {
    # Жизнь Access токена (с ним ходят за данными)
    'ACCESS_TOKEN_LIFETIME': timedelta(days=30), 
    
    # Жизнь Refresh токена (им обновляют Access, если тот протух)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=60),
    
    # Остальное можно оставить по дефолту, но эти два - главные
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

REDIS_HOST = os.getenv('REDIS_HOST', 'localhost')

# === CELERY SETTINGS ===
CELERY_BROKER_URL = f'redis://{REDIS_HOST}:6379/0'
CELERY_RESULT_BACKEND = f'redis://{REDIS_HOST}:6379/0'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

ASGI_APPLICATION = 'config.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(REDIS_HOST, 6379)],
        },
    },
}

gettext = lambda s: s
LANGUAGES = (
    ('ru', gettext('Russian')),
    ('en', gettext('English')),
)

MODELTRANSLATION_DEFAULT_LANGUAGE = 'ru'
MODELTRANSLATION_FALLBACK_LANGUAGES = ('ru', 'en') # Если нет перевода на EN, покажет RU
USE_I18N = True
USE_L10N = True

GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID')
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY')

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
# Позволяет кукам ходить между поддоменами (если нужно) и при POST запросах
CSRF_COOKIE_SAMESITE = 'None'  # Иногда нужно 'Lax', но для кросс-домена часто 'None'
SESSION_COOKIE_SAMESITE = 'None'

JAZZMIN_SETTINGS = {
    "site_title": "careyour.pet Admin",
    "site_header": "careyour.pet",
    "site_brand": "CareYourPet",
    "welcome_sign": "Добро пожаловать в панель управления careyour.pet",
    "copyright": "CareYourPet Ltd",
    "search_model": ["users.User", "pets.Category"], # Поиск по этим моделям в шапке
    
    # Меню сбоку (True) или сверху (False)
    "show_sidebar": True,
    "navigation_expanded": True,
    
    # Иконки для меню (используются FontAwesome)
    "icons": {
        "auth": "fas fa-users-cog",
        "users.User": "fas fa-user",
        "pets.Category": "fas fa-paw",
        "pets.Tag": "fas fa-tags",
        # Добавь свои модели по вкусу
    },
}

# Твики интерфейса (цвета)
JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",   # Попробуй: 'pulse', 'flatly', 'darkly', 'simplex'
    #"dark_mode_theme": "darkly", # Если нужна темная тема
}