# Generated by Django 6.0 on 2026-01-18 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0005_petevent_admin_notes_petevent_guest_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('code', models.CharField(help_text='Уникальный код. Для Германии здесь будет номер GOT.', max_length=50, unique=True, verbose_name='Код / Артикул / GOT')),
                ('item_type', models.CharField(choices=[('service', 'Услуга'), ('good', 'Товар')], default='service', max_length=10, verbose_name='Тип')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='Если 0 - налог не считается', max_digits=5, verbose_name='Налог % (НДС/VAT)')),
                ('is_stock_tracked', models.BooleanField(default=False, verbose_name='Учитывать остатки?')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Остаток на складе')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Товар/Услуга',
                'verbose_name_plural': 'Каталог услуг',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя клиента (Гость)')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('unpaid', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('cancelled', 'Отменен')], default='draft', max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('insurance', 'Страховая'), ('mixed', 'Смешанный')], default='card', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Итого к оплате')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма налога')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Скидка')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки (для внутреннего пользования)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='Клиент (Аккаунт)')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='pets.petevent', verbose_name='Связанное событие')),
                ('pet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='pets.pet', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_at_moment', models.CharField(max_length=200, verbose_name='Название в чеке')),
                ('price_at_moment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('tax_percent_at_moment', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Налог %')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма строки')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.catalogitem', verbose_name='Товар из каталога')),
            ],
            options={
                'verbose_name': 'Позиция чека',
                'verbose_name_plural': 'Позиции чека',
            },
        ),
    ]
