# Generated by Django 6.0 on 2026-01-16 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0003_eventtype_name_en_eventtype_name_ru'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Начало течки')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Конец течки')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(limit_choices_to={'gender': 'F'}, on_delete=django.db.models.deletion.CASCADE, related_name='heat_cycles', to='pets.pet', verbose_name='Питомец (Самка)')),
            ],
            options={
                'verbose_name': 'Цикл (Течка)',
                'verbose_name_plural': 'Циклы (Течки)',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Mating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата вязки')),
                ('is_successful', models.BooleanField(default=False, verbose_name='Беременность подтверждена')),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matings', to='breeding.heatcycle', verbose_name='В рамках цикла')),
                ('dam', models.ForeignKey(limit_choices_to={'gender': 'F'}, on_delete=django.db.models.deletion.CASCADE, related_name='matings_as_dam', to='pets.pet', verbose_name='Мать (Dam)')),
                ('sire', models.ForeignKey(limit_choices_to={'gender': 'M'}, on_delete=django.db.models.deletion.CASCADE, related_name='matings_as_sire', to='pets.pet', verbose_name='Отец (Sire)')),
            ],
            options={
                'verbose_name': 'Вязка',
                'verbose_name_plural': 'Вязки',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Litter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litter_code', models.CharField(max_length=50, verbose_name='Код/Буква помета')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('born_alive', models.PositiveIntegerField(default=0, verbose_name='Рождено живых')),
                ('born_dead', models.PositiveIntegerField(default=0, verbose_name='Мертворожденных')),
                ('dam', models.ForeignKey(limit_choices_to={'gender': 'F'}, on_delete=django.db.models.deletion.PROTECT, related_name='litters', to='pets.pet', verbose_name='Мать')),
                ('offspring', models.ManyToManyField(blank=True, related_name='litter_membership', to='pets.pet', verbose_name='Дети (Карточки)')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litters', to=settings.AUTH_USER_MODEL)),
                ('sire', models.ForeignKey(limit_choices_to={'gender': 'M'}, on_delete=django.db.models.deletion.PROTECT, related_name='sired_litters', to='pets.pet', verbose_name='Отец')),
            ],
            options={
                'verbose_name': 'Помет',
                'verbose_name_plural': 'Пометы',
                'ordering': ['-birth_date'],
                'unique_together': {('owner', 'litter_code')},
            },
        ),
    ]
