# Generated by Django 6.0 on 2025-12-13 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название атрибута')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('unit', models.CharField(blank=True, max_length=100, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Атрибут',
                'verbose_name_plural': 'Атрибуты',
            },
        ),
        migrations.CreateModel(
            name='PetAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Характеристика питомца',
                'verbose_name_plural': 'Характеристики питомцев',
            },
        ),
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pet_images/', verbose_name='Изображение')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основное фото')),
            ],
            options={
                'verbose_name': 'Фото питомца',
                'verbose_name_plural': 'Фото питомцев',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название метки')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Метка',
                'verbose_name_plural': 'Метки',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название вида/категории')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('attributes', models.ManyToManyField(blank=True, to='pets.attribute', verbose_name='Доступные атрибуты')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pets.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Вид/Категория',
                'verbose_name_plural': 'Виды/Категории',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Кличка / Инвентарный номер')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL-слаг')),
                ('description', models.TextField(blank=True, verbose_name='Заметки / Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Жив / Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('categories', models.ManyToManyField(related_name='pets', to='pets.category', verbose_name='Вид/Категория')),
            ],
            options={
                'verbose_name': 'Питомец',
                'verbose_name_plural': 'Питомцы',
            },
        ),
    ]
