# Generated by Django 6.0 on 2025-12-13 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_tag_target_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('vaccine', 'Вакцинация'), ('parasite', 'Обработка от паразитов (Глисты/Блохи)'), ('medical', 'Визит к врачу / Лечение'), ('hygiene', 'Гигиена / Уход'), ('measure', 'Замеры (Вес/Рост)'), ('other', 'Другое')], max_length=20, verbose_name='Тип события')),
                ('title', models.CharField(max_length=255, verbose_name='Название (например, Нобивак)')),
                ('date', models.DateField(verbose_name='Дата события')),
                ('next_date', models.DateField(blank=True, null=True, verbose_name='Дата следующего (Напоминание)')),
                ('description', models.TextField(blank=True, verbose_name='Заметки / Описание')),
                ('document', models.FileField(blank=True, null=True, upload_to='health_docs/', verbose_name='Документ / Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pets.pet', verbose_name='Питомец')),
            ],
            options={
                'verbose_name': 'Событие / Запись',
                'verbose_name_plural': 'Медкарта и События',
                'ordering': ['-date'],
            },
        ),
    ]
