# Generated by Django 6.0 on 2025-12-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_healthevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Метка', 'verbose_name_plural': 'Метки'},
        ),
        migrations.AddField(
            model_name='tag',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Порядок вывода'),
        ),
    ]
