# Generated by Django 6.0 on 2025-12-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0011_healthevent_status_historicalhealthevent_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Вид/Категория', 'verbose_name_plural': 'Виды/Категории'},
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='category_icons/', verbose_name='Иконка (SVG/PNG)'),
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Порядок вывода'),
        ),
    ]
