# Generated by Django 6.0 on 2025-12-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0013_attribute_icon_tag_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='clinic_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ветклиника'),
        ),
    ]
