# Generated by Django 6.0 on 2025-12-15 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0014_pet_clinic_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthevent',
            name='document',
        ),
        migrations.RemoveField(
            model_name='historicalhealthevent',
            name='document',
        ),
        migrations.AlterField(
            model_name='healthevent',
            name='date',
            field=models.DateTimeField(verbose_name='Время события'),
        ),
        migrations.AlterField(
            model_name='healthevent',
            name='next_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Напоминание (Дата и Время)'),
        ),
        migrations.AlterField(
            model_name='healthevent',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='historicalhealthevent',
            name='date',
            field=models.DateTimeField(verbose_name='Время события'),
        ),
        migrations.AlterField(
            model_name='historicalhealthevent',
            name='next_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Напоминание (Дата и Время)'),
        ),
        migrations.AlterField(
            model_name='historicalhealthevent',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='HealthEventAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='health_docs/%Y/%m/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='pets.healthevent', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Вложение (Медкарта)',
                'verbose_name_plural': 'Вложения (Медкарта)',
            },
        ),
        migrations.CreateModel(
            name='PetAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('read', 'Только просмотр'), ('write', 'Просмотр и Запись')], default='read', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='pets.pet', verbose_name='Питомец')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Кому предоставлен доступ (Врач)')),
            ],
            options={
                'verbose_name': 'Доступ к питомцу',
                'verbose_name_plural': 'Доступы к питомцам',
                'unique_together': {('pet', 'user')},
            },
        ),
    ]
