# Generated by Django 6.0 on 2026-01-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название атрибута')),
                ('name_ru', models.CharField(max_length=100, null=True, unique=True, verbose_name='Название атрибута')),
                ('name_en', models.CharField(max_length=100, null=True, unique=True, verbose_name='Название атрибута')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('unit', models.CharField(blank=True, max_length=100, verbose_name='Единица измерения')),
                ('icon', models.FileField(blank=True, null=True, upload_to='attribute_icons/', verbose_name='Иконка (SVG/PNG)')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок вывода')),
                ('is_universal', models.BooleanField(default=False, verbose_name='Универсальный (для всех видов)')),
            ],
            options={
                'verbose_name': 'Атрибут',
                'verbose_name_plural': 'Атрибуты',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название вида/категории')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Название вида/категории')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Название вида/категории')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='category_icons/', verbose_name='Иконка (SVG/PNG)')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок вывода')),
            ],
            options={
                'verbose_name': 'Вид/Категория',
                'verbose_name_plural': 'Виды/Категории',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('medical', 'Медицина'), ('reproduction', 'Репродукция'), ('show', 'Выставки и Документы'), ('care', 'Уход и Гигиена'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория')),
                ('icon', models.FileField(blank=True, null=True, upload_to='event_icons/', verbose_name='Иконка')),
                ('default_schema', models.JSONField(blank=True, default=dict, verbose_name='JSON Схема полей (Metadata Schema)')),
                ('is_universal', models.BooleanField(default=True, verbose_name='Общий для всех')),
            ],
            options={
                'verbose_name': 'Тип события',
                'verbose_name_plural': 'Типы событий',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Кличка / Инвентарный номер')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL-слаг')),
                ('description', models.TextField(blank=True, verbose_name='Заметки / Описание')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Мальчик'), ('F', 'Девочка')], max_length=1, verbose_name='Пол')),
                ('clinic_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ветклиника')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('temp_owner_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя владельца (Временное)')),
                ('temp_owner_phone', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Телефон владельца (для связи)')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичный профиль (В ленту)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Жив / Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Питомец',
                'verbose_name_plural': 'Питомцы',
            },
        ),
        migrations.CreateModel(
            name='PetAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('read', 'Только просмотр'), ('write', 'Просмотр и Запись')], default='read', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Доступ к питомцу',
                'verbose_name_plural': 'Доступы к питомцам',
            },
        ),
        migrations.CreateModel(
            name='PetAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Характеристика питомца',
                'verbose_name_plural': 'Характеристики питомцев',
            },
        ),
        migrations.CreateModel(
            name='PetEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата события')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные (Metadata)')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('completed', 'Выполнено'), ('missed', 'Пропущено')], default='completed', max_length=20, verbose_name='Статус')),
                ('next_date', models.DateField(blank=True, null=True, verbose_name='Дата следующего события')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False, verbose_name='Подтверждено врачом')),
            ],
            options={
                'verbose_name': 'Событие питомца',
                'verbose_name_plural': 'События питомца',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PetEventAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='event_docs/%Y/%m/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
            },
        ),
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pet_images/', verbose_name='Изображение')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основное фото')),
            ],
            options={
                'verbose_name': 'Фото питомца',
                'verbose_name_plural': 'Фото питомцев',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название метки')),
                ('name_ru', models.CharField(max_length=100, null=True, unique=True, verbose_name='Название метки')),
                ('name_en', models.CharField(max_length=100, null=True, unique=True, verbose_name='Название метки')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('target_gender', models.CharField(blank=True, choices=[('M', 'Только мальчики'), ('F', 'Только девочки')], max_length=1, null=True, verbose_name='Ограничение по полу')),
                ('icon', models.FileField(blank=True, null=True, upload_to='attribute_icons/', verbose_name='Иконка (SVG/PNG)')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок вывода')),
                ('is_universal', models.BooleanField(default=False, verbose_name='Универсальный (для всех видов)')),
            ],
            options={
                'verbose_name': 'Метка',
                'verbose_name_plural': 'Метки',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
