# Generated by Django 6.0 on 2026-01-16 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_attributes', to=settings.AUTH_USER_MODEL, verbose_name='Создатель (если кастомный)'),
        ),
        migrations.AddField(
            model_name='category',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='pets.attribute', verbose_name='Доступные атрибуты'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pets.category', verbose_name='Родительская категория'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_event_types', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='pet',
            name='categories',
            field=models.ManyToManyField(related_name='pets', to='pets.category', verbose_name='Вид/Категория'),
        ),
        migrations.AddField(
            model_name='pet',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pets', to=settings.AUTH_USER_MODEL, verbose_name='Кем создана карточка (Врач)'),
        ),
        migrations.AddField(
            model_name='pet',
            name='father',
            field=models.ForeignKey(blank=True, limit_choices_to={'gender': 'M'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_father', to='pets.pet', verbose_name='Отец'),
        ),
        migrations.AddField(
            model_name='pet',
            name='mother',
            field=models.ForeignKey(blank=True, limit_choices_to={'gender': 'F'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_mother', to='pets.pet', verbose_name='Мать'),
        ),
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='pet',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pet_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='petaccess',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='pets.pet', verbose_name='Питомец'),
        ),
        migrations.AddField(
            model_name='petaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Кому предоставлен доступ (Врач)'),
        ),
        migrations.AddField(
            model_name='petattribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.attribute', verbose_name='Атрибут'),
        ),
        migrations.AddField(
            model_name='petattribute',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='pets.pet', verbose_name='Питомец'),
        ),
        migrations.AddField(
            model_name='petevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи'),
        ),
        migrations.AddField(
            model_name='petevent',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='pets.eventtype', verbose_name='Тип события'),
        ),
        migrations.AddField(
            model_name='petevent',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pets.pet', verbose_name='Питомец'),
        ),
        migrations.AddField(
            model_name='peteventattachment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='pets.petevent', verbose_name='Событие'),
        ),
        migrations.AddField(
            model_name='petimage',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pets.pet', verbose_name='Питомец'),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_tags', to=settings.AUTH_USER_MODEL, verbose_name='Создатель (если кастомный)'),
        ),
        migrations.AddField(
            model_name='pet',
            name='tags',
            field=models.ManyToManyField(blank=True, to='pets.tag', verbose_name='Метки'),
        ),
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.ManyToManyField(blank=True, to='pets.tag', verbose_name='Метки категории'),
        ),
        migrations.AlterUniqueTogether(
            name='petaccess',
            unique_together={('pet', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='petattribute',
            unique_together={('pet', 'attribute')},
        ),
    ]
