# Generated by Django 6.0 on 2025-12-13 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='petattribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.attribute', verbose_name='Атрибут'),
        ),
        migrations.AddField(
            model_name='petattribute',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='pets.pet', verbose_name='Питомец'),
        ),
        migrations.AddField(
            model_name='petimage',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pets.pet', verbose_name='Питомец'),
        ),
        migrations.AddField(
            model_name='pet',
            name='tags',
            field=models.ManyToManyField(blank=True, to='pets.tag', verbose_name='Метки'),
        ),
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.ManyToManyField(blank=True, to='pets.tag', verbose_name='Метки категории'),
        ),
        migrations.AlterUniqueTogether(
            name='petattribute',
            unique_together={('pet', 'attribute')},
        ),
    ]
