# Generated by Django 6.0 on 2025-12-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мальчик'), ('F', 'Девочка')], max_length=1),
        ),
    ]
