# Generated by Django 6.0 on 2026-01-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_eventtype_name_en_eventtype_name_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petevent',
            name='date',
            field=models.DateTimeField(verbose_name='Дата и время события'),
        ),
        migrations.AlterField(
            model_name='petevent',
            name='next_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата следующего события'),
        ),
    ]
