# Generated by Django 6.0 on 2026-01-18 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_petevent_date_alter_petevent_next_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='petevent',
            name='admin_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Заметки администратора'),
        ),
        migrations.AddField(
            model_name='petevent',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя клиента (Гость)'),
        ),
        migrations.AddField(
            model_name='petevent',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон (Гость)'),
        ),
        migrations.AlterField(
            model_name='petevent',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pets.pet', verbose_name='Питомец'),
        ),
    ]
