# Generated by Django 6.0 on 2025-12-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_attribute_options_attribute_sort_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='target_gender',
            field=models.CharField(blank=True, choices=[('M', 'Только мальчики'), ('F', 'Только девочки')], max_length=1, null=True, verbose_name='Ограничение по полу'),
        ),
    ]
