# Generated by Django 6.0 on 2026-01-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_petevent_admin_notes_petevent_guest_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='attr_type',
            field=models.CharField(choices=[('text', 'Текст (строка)'), ('number', 'Число'), ('select', 'Выбор из списка'), ('checkbox', 'Да/Нет (Checkbox)'), ('date', 'Дата')], default='text', max_length=20, verbose_name='Тип ввода'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text="Только для типа 'Выбор из списка'. Пример: ['Короткая', 'Длинная']", verbose_name='Опции выбора'),
        ),
    ]
