# Generated by Django 6.0 on 2025-12-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_alter_tag_options_tag_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Публичный профиль (В ленту)'),
        ),
    ]
