# Generated by Django 6.0 on 2025-12-13 15:46

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_healthevent_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='healthevent',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Подтверждено врачом'),
        ),
        migrations.CreateModel(
            name='HistoricalHealthEvent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('vaccine', 'Вакцинация'), ('parasite', 'Обработка от паразитов (Глисты/Блохи)'), ('medical', 'Визит к врачу / Лечение'), ('hygiene', 'Гигиена / Уход'), ('measure', 'Замеры (Вес/Рост)'), ('other', 'Другое')], max_length=20, verbose_name='Тип события')),
                ('title', models.CharField(max_length=255, verbose_name='Название (например, Нобивак)')),
                ('date', models.DateField(verbose_name='Дата события')),
                ('next_date', models.DateField(blank=True, null=True, verbose_name='Дата следующего (Напоминание)')),
                ('description', models.TextField(blank=True, verbose_name='Заметки / Описание')),
                ('document', models.TextField(blank=True, max_length=100, null=True, verbose_name='Документ / Фото')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Подтверждено врачом')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем создана запись')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pets.pet', verbose_name='Питомец')),
            ],
            options={
                'verbose_name': 'historical Событие / Запись',
                'verbose_name_plural': 'historical Медкарта и События',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
