# Generated by Django 6.0 on 2025-12-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0010_healthevent_is_verified_historicalhealthevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthevent',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланировано'), ('confirmed', 'Подтверждено'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='completed', max_length=20, verbose_name='Статус события'),
        ),
        migrations.AddField(
            model_name='historicalhealthevent',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланировано'), ('confirmed', 'Подтверждено'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='completed', max_length=20, verbose_name='Статус события'),
        ),
    ]
