# Generated by Django 6.0 on 2025-12-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0012_alter_category_options_category_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='attribute_icons/', verbose_name='Иконка (SVG/PNG)'),
        ),
        migrations.AddField(
            model_name='tag',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='attribute_icons/', verbose_name='Иконка (SVG/PNG)'),
        ),
    ]
