# Generated by Django 6.0 on 2026-01-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0016_pet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Название атрибута'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Название атрибута'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название вида/категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название вида/категории'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Название метки'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Название метки'),
        ),
    ]
