# Generated by Django 6.0 on 2026-01-12 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0017_attribute_name_en_attribute_name_ru_category_name_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pets', to=settings.AUTH_USER_MODEL, verbose_name='Кем создана карточка (Врач)'),
        ),
        migrations.AddField(
            model_name='pet',
            name='temp_owner_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя владельца (Временное)'),
        ),
        migrations.AddField(
            model_name='pet',
            name='temp_owner_phone',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Телефон владельца (для связи)'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
