# Generated by Django 6.0 on 2026-01-16 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0018_pet_created_by_pet_temp_owner_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_attributes', to=settings.AUTH_USER_MODEL, verbose_name='Создатель (если кастомный)'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='is_universal',
            field=models.BooleanField(default=False, verbose_name='Универсальный (для всех видов)'),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_tags', to=settings.AUTH_USER_MODEL, verbose_name='Создатель (если кастомный)'),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_universal',
            field=models.BooleanField(default=False, verbose_name='Универсальный (для всех видов)'),
        ),
    ]
