# Generated by Django 6.0 on 2026-01-10 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_about_user_telegram_user_work_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('phone', 'Телефон'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('instagram', 'Instagram'), ('email', 'Email'), ('site', 'Сайт'), ('vk', 'VK'), ('other', 'Другое')], default='phone', max_length=20)),
                ('value', models.CharField(help_text='Номер телефона, никнейм или ссылка', max_length=255)),
                ('label', models.CharField(blank=True, help_text="Например: 'Рабочий', 'Личный', 'Для записи'", max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
