# Generated by Django 6.0 on 2026-01-11 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usercontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='VetVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_image', models.ImageField(upload_to='vet_docs/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Причина отказа (видна пользователю)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка на ветеринара',
                'verbose_name_plural': 'Заявки на ветеринаров',
                'ordering': ['-created_at'],
            },
        ),
    ]
